; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "VR Downtown Driving"
#define MyAppVersion "0.2.7"
#define MyAppPublisher "Daniel Boxer"
#define MyAppURL "https://github.com/danielboxer/vr-downtown-driving"
#define MyAppExeName "VR Downtown Driving.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7E487450-545A-487D-B6DA-D3FF2274A6F1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; The installer requires admin rights because SUMO's MSI installs to Program Files.
PrivilegesRequired=admin
OutputDir={#SourcePath}build\installer
OutputBaseFilename=VRDowntownDriving-Setup-{#MyAppVersion}-x64
SolidCompression=yes
Compression=lzma2
MinVersion=10.0
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "sumo"; Description: "Install SUMO 1.22.0 (required for running traffic simulations)"; GroupDescription: "Dependencies:"

[Files]
Source: "{#SourcePath}build\StandaloneWindows64\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}build\StandaloneWindows64\D3D12\*"; DestDir: "{app}\D3D12"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourcePath}build\StandaloneWindows64\VR Downtown Driving_Data\*"; DestDir: "{app}\VR Downtown Driving_Data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourcePath}build\StandaloneWindows64\baselib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}build\StandaloneWindows64\GameAssembly.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}build\StandaloneWindows64\UnityCrashHandler64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}build\StandaloneWindows64\UnityPlayer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}build\ScenarioManager.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}Scenarios\*"; DestDir: "{app}\Scenarios"; Flags: ignoreversion recursesubdirs createallsubdirs
; SUMO is bundled so users do not need to install it separately.
; The MSI is extracted to {tmp} and deleted after the installation completes.
Source: "{#SourcePath}build\sumo-win64-1.22.0.msi"; DestDir: "{tmp}"; Flags: deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Install SUMO silently before launching the app (only if the user kept the task checked).
Filename: msiexec.exe; Parameters: "/i ""{tmp}\sumo-win64-1.22.0.msi"" /quiet /norestart"; StatusMsg: "Installing SUMO 1.22.0 (this may take a moment)..."; Tasks: sumo; Flags: waituntilterminated
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

